config/routes.rb
Rails.application.routes.draw do
  resources :posts 

  devise_for :users


    devise_scope :user do
      get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user'
      put 'users', to: 'devise/registrations#update', as: 'update_user'
    end
  
    devise_scope :user do
      get 'users/edit_password', to: 'devise/passwords#edit', as: 'edit_password'
      put 'users/update_password', to: 'devise/passwords#update', as: 'update_password'
    end
  resources :reactions, only: [:create]
  resources :comments, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'new_user_reaction/:post_id/:kind', to: 'reactions#new_user_reaction', as: 'new_user_reaction'

  # Defines the root path route ("/")
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :reactions, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    has_many :users, through: :reactions

    Kinds = %w[like dislike not_interested neutral].freeze
    KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta", "not_interested" => "No me interesa", "neutral" => "Neutral"}.freeze
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user
  belongs_to :comment, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :reactions
        has_many :comments
        has_many :post, through: :reactions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
    end

    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
    @post = Post.find(params[:comment][:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
    if @comment.save
    format.html { redirect_to post_path(@post.id), notice:
    'Comment was successfully created.' }
    else
    format.html { redirect_to post_path(@post.id), notice:
    'Comment was not created.' }
    end
    end
    end
    private
    def comment_params
    params.require(:comment).permit(:content, :post_id)
    end
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  include ApplicationHelper

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
  end
    
  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :place, :when_went)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_post_and_comment, only: [:new_user_reaction]

  def new_user_reaction
    @user = current_user
    @type = params[:reaction_type]
    @kind = params[:kind]

    respond_to do |format|
      if @type == "comment" && @comment.nil?
        format.html { redirect_to posts_path, notice: 'Invalid comment' }
      elsif @type == "post" && @post.nil?
        format.html { redirect_to posts_path, notice: 'Invalid post' }
      else
        if @type == "post" && @post.present?
          @reaction = Reaction.new(user_id: @user.id, post_id: @post.id, reaction_type: @type, kind: @kind)
        elsif @type == "comment" && @comment.present?
          @reaction = Reaction.new(user_id: @user.id, comment_id: @comment.id, reaction_type: @type, kind: @kind)
        end

        if @reaction&.save
          format.html { redirect_to post_path(@post), notice: 'Reaction was successfully created.' }
        else
          format.html { redirect_to post_path(@post), notice: 'Something went wrong' }
        end
      end
    end
  end

  private

  def set_post_and_comment
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.find_by(id: params[:comment_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def kind_to_bootstrap_class(kind)
      case kind
      when "like"
        "btn-primary"
      when "dislike"
        "btn-danger"
      when "not_interested"
        "btn-warning"
      when "neutral"
        "btn-secondary"
      else
        "btn-secondary"
      end
    end
  end
  

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
<% if @comment.errors.any? %>
<div id = 'error_explanation'>
<h2>Este comentario no se pudo crear por las siguientes
razones</h2>
<ul>
<% @comment.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
 <%= f.hidden_field :post_id, value: @post.id %>

  <div class="mb-3">
    <%= f.label :content, "Comentario:", class: "mt-2 form-label fw-bold" %>
    <%= f.text_area :content, class: "form-control", rows: 3 %>
  </div>

  <div class="text-center">
    <%= f.submit "Crear Comentario", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Crazy4Cats</a>
  
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Show Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Post", new_post_path, class: "nav-link" %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <ul class="navbar-nav ml-auto"> 
        <li class="nav-item">
          <%= link_to "Edit User", edit_user_path(current_user), class: "nav-link" %>
        </li>
        <%= form_with url: destroy_user_session_path, method: :delete do |f| %>
          <li class="nav-item">
            <%= f.submit "Sign Out", class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <ul class="navbar-nav ml-auto"> 
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>



  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { class: "container" }) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :when_went, class: "form-label" %>
    <%= form.datetime_field :when_went, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Create Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>

    <p class="card-text">
      <strong>Description:</strong>
      <%= post.description %>
    </p>

    <p class="card-text">
      <strong>When went:</strong>
      <%= post.when_went %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Crazy4Cats Posts</h1>
<p>
  <%= link_to "New post", new_post_path, class: "mt-2 btn btn-primary" %>
</p>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
<p>
  <%= link_to "Show this post", post, class: "mt-2 btn btn-primary" %>
</p>

  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Crazy4Cats New post</h1>
<div class="container">
  <%= render "form", post: @post %>
</div>
<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div class="mt-2 btn-group d-flex justify-content-center" role="group" aria-label="Reactions">
  <% Post::Kinds.each do |kind| %>
    <button type="button" class="btn <%= kind_to_bootstrap_class(kind) %>">
      <%= "#{Post::KindsSpanish[kind]}: #{@post.reactions.where(kind: kind).count}" %>
    </button>
  <% end %>
</div>
<%= render 'comments/form' %>
<div>
<%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-success" %> 
<%= link_to "Back to posts", posts_path, class: "btn btn-info" %>

<%= link_to "Destroy this post", @post, method: :delete, class: "btn btn-danger" %>

<div class="gap-1 mt-3 btn-group d-flex justify-content-center" role="group" aria-label="Reactions">
  <% Post::Kinds.each do |kind| %>
    <%= button_to "#{Post::KindsSpanish[kind]}: #{@post.reactions.where(kind: kind).count}",
                  new_user_reaction_path(post_id: @post.id, reaction_type: "post", kind: kind),
                  method: :post,
                  class: "btn #{kind_to_bootstrap_class(kind)}" %>
  <% end %>
</div>

</div>
<div class="mt-3">
  <h2>Comments:</h2>
  <div class="list-group">
    <% @post.comments.each do |comment| %>
      <div class="list-group-item">
        <h5 class="mb-1">User: <%= comment.user.email %></h5>
        <p class="mb-1">Content: <%= comment.content %></p>
      </div>
    <% end %>
  </div>
</div>